/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro.domains.users;

@org.apache.avro.specific.AvroGenerated
public interface UserProto {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"UserProto\",\"namespace\":\"example.avro.domains.users\",\"types\":[{\"type\":\"record\",\"name\":\"User\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\"}]}],\"messages\":{\"add\":{\"request\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"age\",\"type\":\"int\",\"default\":0}],\"response\":\"User\"},\"getById\":{\"request\":[{\"name\":\"id\",\"type\":\"long\"}],\"response\":\"User\"}}}");
  /**
   */
  example.avro.domains.users.User add(java.lang.CharSequence name, int age);
  /**
   */
  example.avro.domains.users.User getById(long id);

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends UserProto {
    public static final org.apache.avro.Protocol PROTOCOL = example.avro.domains.users.UserProto.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void add(java.lang.CharSequence name, int age, org.apache.avro.ipc.Callback<example.avro.domains.users.User> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getById(long id, org.apache.avro.ipc.Callback<example.avro.domains.users.User> callback) throws java.io.IOException;
  }
}